### ISSUE TITLE
BurntCocoaUI

### ISSUE THREAD

**Issue by BurntCaramel** [joeljfischer/awesome-apple#5]
Hi,

This looks like a really nice list of resources. Your Mac UI list is a little short, so thought you may be interested in my declarative UI assistants for Mac: https://github.com/BurntCaramel/BurntCocoaUI

I also have some Mac/iOS model classes, https://github.com/BurntCaramel/GLAArrayEditing and optional integration with Mantle https://github.com/BurntCaramel/GLAArray-Mantle

Thanks

**Comment by joeljfischer** [comment]
Thanks for the PR! Unfortunately since I can't verify it for myself and it's not a well-known and used package within the community, I'm going to close this issue. Thanks for the info though, if I ever work on a Mac project again, I'll take a look!
